manifest:
    version: "1.2"

    self:
        path: telos

    projects:
        - name: zephyr
          url: https://github.com/zephyrproject-rtos/zephyr
          revision: v4.4.0
          import: true
