#!/usr/bin/env python3

import argparse
import pathlib
import sys
import tomllib


def render(manifest: pathlib.Path) -> str:
    document = tomllib.loads(manifest.read_text(encoding="utf-8"))
    sources: list[str] = []
    for component in document.get("component", {}).values():
        sources.extend(component.get("sources", []))
    if not sources or len(sources) != len(set(sources)):
        raise ValueError("component sources must be non-empty and unique")
    lines = [
        "# Generated by tools/generate_zephyr_sources.py. Do not edit.",
        "zephyr_library_sources(",
    ]
    lines.extend(
        f"    ${{CMAKE_CURRENT_LIST_DIR}}/../../../{source}"
        for source in sources
    )
    lines.append(")")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected = render(arguments.manifest)
    if arguments.check:
        if not arguments.output.exists():
            print("generated Zephyr source manifest is missing", file=sys.stderr)
            return 1
        if arguments.output.read_text(encoding="utf-8") != expected:
            print("generated Zephyr source manifest is stale", file=sys.stderr)
            return 1
        return 0
    arguments.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
