# Generated by tools/generate_zephyr_sources.py. Do not edit.
zephyr_library_sources(
    ${CMAKE_CURRENT_LIST_DIR}/../../../src/base/error.c
    ${CMAKE_CURRENT_LIST_DIR}/../../../src/base/event.c
    ${CMAKE_CURRENT_LIST_DIR}/../../../src/base/id.c
    ${CMAKE_CURRENT_LIST_DIR}/../../../src/base/value.c
    ${CMAKE_CURRENT_LIST_DIR}/../../../src/base/value_json.c
    ${CMAKE_CURRENT_LIST_DIR}/../../../src/state/session.c
)
